[project]
name = "mri-segmentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nibabel>=5.3.2",
    "notebook>=7.4.5",
]
